// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pipe_trackerEvent struct {
	_    structs.HostLayout
	Pid  uint32
	Fd   int32
	Ts   uint64
	Comm [16]int8
}

// loadPipe_tracker returns the embedded CollectionSpec for pipe_tracker.
func loadPipe_tracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Pipe_trackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pipe_tracker: %w", err)
	}

	return spec, err
}

// loadPipe_trackerObjects loads pipe_tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pipe_trackerObjects
//	*pipe_trackerPrograms
//	*pipe_trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPipe_trackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPipe_tracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pipe_trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pipe_trackerSpecs struct {
	pipe_trackerProgramSpecs
	pipe_trackerMapSpecs
	pipe_trackerVariableSpecs
}

// pipe_trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pipe_trackerProgramSpecs struct {
	KprobeWrite *ebpf.ProgramSpec `ebpf:"kprobe_write"`
}

// pipe_trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pipe_trackerMapSpecs struct {
	Writes *ebpf.MapSpec `ebpf:"writes"`
}

// pipe_trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pipe_trackerVariableSpecs struct {
}

// pipe_trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPipe_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type pipe_trackerObjects struct {
	pipe_trackerPrograms
	pipe_trackerMaps
	pipe_trackerVariables
}

func (o *pipe_trackerObjects) Close() error {
	return _Pipe_trackerClose(
		&o.pipe_trackerPrograms,
		&o.pipe_trackerMaps,
	)
}

// pipe_trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPipe_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type pipe_trackerMaps struct {
	Writes *ebpf.Map `ebpf:"writes"`
}

func (m *pipe_trackerMaps) Close() error {
	return _Pipe_trackerClose(
		m.Writes,
	)
}

// pipe_trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPipe_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type pipe_trackerVariables struct {
}

// pipe_trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPipe_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type pipe_trackerPrograms struct {
	KprobeWrite *ebpf.Program `ebpf:"kprobe_write"`
}

func (p *pipe_trackerPrograms) Close() error {
	return _Pipe_trackerClose(
		p.KprobeWrite,
	)
}

func _Pipe_trackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pipe_tracker_bpfel.o
var _Pipe_trackerBytes []byte
